countries_list = {
    "albania" : "https://ee24.com/partners/albania/",
    "andorra" : "https://ee24.com/partners/andorra/",
    "austria" : "https://ee24.com/partners/austria/",
    "belgium" : "https://ee24.com/partners/belgium/",
    "bosnia-and-herzegovina" : "https://ee24.com/partners/bosnia-and-herzegovina/",
    "bulgaria" : "https://ee24.com/partners/bulgaria/",
    "croatia" : "https://ee24.com/partners/croatia/",
    "cyprus" : "https://ee24.com/partners/cyprus/",
    "czech-republic" : "https://ee24.com/partners/czech-republic/",
    "denmark" : "https://ee24.com/partners/denmark/",
    "estonia" : "https://ee24.com/partners/estonia/",
    "finland" : "https://ee24.com/partners/finland/",
    "france" : "https://ee24.com/partners/france/",
    "germany" : "https://ee24.com/partners/germany/",
    "greece" : "https://ee24.com/partners/greece/",
    "hungary" : "https://ee24.com/partners/hungary/",
    "iceland" : "https://ee24.com/partners/iceland/",
    "ireland" : "https://ee24.com/partners/ireland/",
    "italy" : "https://ee24.com/partners/italy/",
    "latvia" : "https://ee24.com/partners/latvia/",
    "lithuania" : "https://ee24.com/partners/lithuania/",
    "luxembourg" : "https://ee24.com/partners/luxembourg/",
    "macedonia" : "https://ee24.com/partners/macedonia/",
    "malta" : "https://ee24.com/partners/malta/",
    "monaco" : "https://ee24.com/partners/monaco/",
    "montenegro" : "https://ee24.com/partners/montenegro/",
    "netherlands" : "https://ee24.com/partners/netherlands/",
    "northern-cyprus" : "https://ee24.com/partners/northern-cyprus/",
    "norway" : "https://ee24.com/partners/norway/",
    "poland" : "https://ee24.com/partners/poland/",
    "portugal" : "https://ee24.com/partners/portugal/",
    "romania" : "https://ee24.com/partners/romania/",
    
    
}
